### ISSUE TITLE
[Python] Subscriber.poll() is unusable in Python

### ISSUE THREAD

**Issue by 1wilkens** [zeek/broker#109]
The `subscriber.poll()` function is currently not usable via Python, as pybind complains about unconvertable types. The following excerpt from a Python REPL illustrates the issue.

```python
>>> q = ep.make_subscriber("foo")
>>> q
<broker.Subscriber object at 0x7fbf65886430>
>>> q.poll()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/broker/__init__.py", line 145, in poll
    msgs = self._subscriber.poll()
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: broker._broker.SubscriberBase) -> std::vector<caf::cow_tuple<broker::topic, broker::data>, std::allocator<caf::cow_tuple<broker::topic, broker::data> > >

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

I vaguely recall this issue appearing some time ago for other functions which needed additional annotations to work w/ pybind. Also I am 99% sure, that I used `poll()` successfully in the past. Did this happen because of the switch to `caf::cow_tuple`?

**Comment by jsiwek** [comment]
Thanks.  Yeah, I think the `cow_tuple` changes a while ago were a breaking change and looked like the `get()` methods of the Python bindings were adapted to convert internally, but the `poll()` method was missed (no test case).  Patch incoming via #110
