### ISSUE TITLE
store_events currently give no way to determine the store an event belongs to

### ISSUE THREAD

**Issue by 0xxon** [zeek/broker#119]
This is kind of an addition that was already discussed in https://github.com/zeek/broker/pull/100, but then got forgotten (I think).

It is now possible to receive store events. However there seems to be no way to determine which store an event actually was sent from. Since we will have several of them simultaneously this is kind of important :)

As John noted in #100 , having the store id in the event as well as the topic seems like the best way.

**Comment by jsiwek** [comment]
> having the store id in the event as well as the topic seems like the best way.

Yeah, maybe didn't get fully realized. @Neverlord mind taking a look?

The part of including the store name in the topic seems easy:

```diff
diff --git a/src/detail/store_actor.cc b/src/detail/store_actor.cc
index 33eda60..e1c1dbf 100644
--- a/src/detail/store_actor.cc
+++ b/src/detail/store_actor.cc
@@ -64,7 +64,7 @@ void store_actor_state::emit_insert_event(const data& key, const data& value,
   vector xs;
   fill_vector(xs, "insert"s, key, value, expiry, publisher);
   self->send(core, atom::publish_v, atom::local_v,
-	      make_data_message(topics::store_events, data{std::move(xs)}));
+	      make_data_message(topics::store_events / id, data{std::move(xs)}));
 }

 void store_actor_state::emit_update_event(const data& key,
@@ -75,7 +75,7 @@ void store_actor_state::emit_update_event(const data& key,
   vector xs;
   fill_vector(xs, "update"s, key, old_value, new_value, expiry, publisher);
   self->send(core, atom::publish_v, atom::local_v,
-	      make_data_message(topics::store_events, data{std::move(xs)}));
+	      make_data_message(topics::store_events / id, data{std::move(xs)}));
 }

 void store_actor_state::emit_erase_event(const data& key,
@@ -83,7 +83,7 @@ void store_actor_state::emit_erase_event(const data& key,
   vector xs;
   fill_vector(xs, "erase"s, key, publisher);
   self->send(core, atom::publish_v, atom::local_v,
-	      make_data_message(topics::store_events, data{std::move(xs)}));
+	      make_data_message(topics::store_events / id, data{std::move(xs)}));
 }

 } // namespace broker::detail
```

But didn't look too far into whether changing the `publisher_id` has much complexity.  The reason it seems not usable at the moment is that it carries identifying information of data's originator (which may be a remote `master`), but what Johanna may need is identifying information of the thing emitting the `store_event` itself (i.e. possibly the local `clone`).

Quick example usage I'm imagining on the Zeek-side:

```diff
diff --git a/src/broker/Manager.cc b/src/broker/Manager.cc
index d54b06158..ba8d10fe5 100644
--- a/src/broker/Manager.cc
+++ b/src/broker/Manager.cc
@@ -819,6 +822,33 @@ bool Manager::Unsubscribe(const string& topic_prefix)

 void Manager::DispatchMessage(const broker::topic& topic, broker::data msg)
	{
+	if ( auto insert = broker::store_event::insert::make(msg) )
+		{
+		// Parsing a store name from topic string will work, but may be more
+		// convenient for the store_event to carry better identifier (store name).
+		auto topic_parts = broker::topic::split(topic);
+		const auto& store_name = topic_parts.back();
+		auto handle = LookupStore(store_name);
+
+		if ( handle )
+			printf("Got insert event for known store %s: %s\n",
+			       store_name.data(), broker::to_string(msg).data());
```

**Comment by 0xxon** [comment]
The publisher ID also is needed - and works fine for what it was intended (figuring out if a message originated from the local node). So - changing that might also not be a good idea.

For my use-case don't really mind either way (just having the store-name in the event is enough). But - it feels like it would be nice to also have it in the event itself.

(Also - note that this is not currently blocking me from continuing my implementation. For the moment I have a stupid-but-working workaround)
