### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by rsmmr** [zeek/broker#139]
This is a warning I keep seeing with current master:

```
Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/_broker.cpp.o
../auxil/broker/bindings/python/_broker.cpp:104:19: warning: explicitly assigning value of variable of type 'const pybind11::detail::self_t' to itself [-Wself-assign-overloaded]
    .def(py::self /= py::self,
         ~~~~~~~~ ^  ~~~~~~~~
1 warning generated.
```

Haven't investigated further yet, but would be nice to fix.

**Comment by timwoj** [comment]
This is apparently just how it's done in python and most people silence the warning. Only clang appears to be warning about it. GCC is fine with it.

**Comment by rsmmr** [comment]
ok, then we should silence as well?
