### ISSUE TITLE
FindBroker.cmake doesn't get installed with Broker

### ISSUE THREAD

**Issue by sethhall** [zeek/broker#185]
I'm not sure if the `FindBroker.cmake` script should be installed since I read that in this scenario it would usually be something more like `BrokerConfig.cmake` that would get installed with the library.

Regardless, if Broker is installed by itself we get a `CAFConfig.cmake` file installed, but no file to help with finding Broker in other Cmake based builds using Broker.

**Comment by Neverlord** [comment]
> I'm not sure if the `FindBroker.cmake` script should be installed

I think not, since the script wouldn't be able to find its own CAF dependency when installing into a non-default location. I think writing a CMake package file (`BrokerConfig.cmake`, as you've pointed out) is the right approach.

**Comment by Neverlord** [comment]
I've added the necessary setup for `BrokerConfig.cmake` in CMake: https://github.com/zeek/broker/blob/cdc8b130adcf3c70dd2bd972fff7880037b4b24a/CMakeLists.txt#L480. Since we also no longer need to find CAF, this should take care of things.

**Comment by Neverlord** [comment]
@0xxon IIRC, you've already updated the OBS scripts to install the new CMake config files, no? Then there's probably nothing left to do here since CAF is no longer exposed anyways.

**Comment by rsmmr** [comment]
Can this be closed?

**Comment by Neverlord** [comment]
I believe so, the OBS adjustment should block this ticket.
