### ISSUE TITLE
Version.hh incorrect for release/2.1 branch

### ISSUE THREAD

**Issue by emillynge** [zeek/broker#195]
Hi Maintainers.

I was compiling from tag v2.1.0 and was surprised to see that the reported version from 
`broker._broker.Version` was 2.2.0-dev

It seems that 40ba9457dee60c31e122521fd8d702d67511161a only changed `VERSION` and forgot `include/broker/version.hh`

**Comment by timwoj** [comment]
Thank you for the report. This is fixed on the branch now.
