### ISSUE TITLE
Publishing more than #free_capacity events blocks indefinitely

### ISSUE THREAD

**Issue by pza94** [zeek/broker#196]
Hi,
we have a Python daemon that publishes events to bro/zeek, which was working fine until we tried to upgrade broker from 1.1.2 to 2.1.0. We noticed that it gets stuck intermittently. After investigating it we realized this happens every time we publish a batch of size `>= publisher.free_capacity()`. 

It was clear that the program was stuck within a native operation: the GIL was taken and the other threads we had in the application were also stuck. The CPU usage was essentially 0 after the application got stuck, indicating that it wasn't caused by getting stuck in an infinite loop.

The issue can be easily reproduced by this short script:

```
import time
import broker


def main():
    ep1 = broker.Endpoint()
    ep2 = broker.Endpoint()
    port = ep1.listen("127.0.0.1", 0)
    subscriber = ep1.make_subscriber("/test")
    ep2.peer("127.0.0.1", port)
    publisher = ep2.make_publisher("/test")
    data = "data"
    publisher.publish_batch(*((data,) for i in range(29)))
    print("29 sent")
    time.sleep(1)
    publisher.publish_batch(*((data,) for i in range(30)))  # blocks indefinitely
    print("this is never reached :(")


if __name__ == '__main__':
    main()

```
The hardcoded capacity of the queue of the publisher is 30,  and apparently whenever it is reached the process gets stuck.
We implemented some logic that makes sure we never publish a batch over the size of the free capacity to avoid this, but it would be nice if this could get fixed upstream.

Bests,
Peter

**Comment by Neverlord** [comment]
Thanks for reporting! After reviewing the code in question, it seems like there's no "slicing" of batches if they exceed the queue capacity. I'm working on a fix.
