### ISSUE TITLE
Error in ./configure

### ISSUE THREAD

**Issue by CrutzPan** [zeek/broker#203]
Hello! 

I am having errors while building the project, i can't execute the ./configure file correctly. The error i get is:

`/path/broker/build/CMakeFiles/CMakeTmp/src.cxx: In function ‘int ### main(int, char**)’:
/path/broker/build/CMakeFiles/CMakeTmp/src.cxx:5:21: error: ‘std::filesystem’ has not been declared
    5 |     auto cwd = std::filesystem::current_path();
      |                     ^~~~~~~~~~
gmake[1]: *** [CMakeFiles/cmTC_6c037.dir/build.make:85: CMakeFiles/cmTC_6c037.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/path/broker/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_6c037/fast] Error 2`

I didn't find a fix to this issue yet, does someone know how to fix it?

Best regards and thank you!

**Comment by timwoj** [comment]
What OS/compiler?

**Comment by CrutzPan** [comment]
OS: Ubuntu 21.04
Compiler Vesion: cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

**Comment by ckreibich** [comment]
I tried a few things to reproduce this but can't ... could you show us the invocation and the output leading up to the error? Are you building from master, a git tag, a tarball?

**Comment by CrutzPan** [comment]
Thanks for the effort! I did the standard process which provoked this error: I checked out the repository from the master branch, made sure all prerequisites are installed and executed the ./configure in the checked out directory. 

I attached the Shell Output, and also the logfiles of cmake.

In the meantime i tried different things like setting the environment variable for CFlags and CXXFlags manually, but that didn't help either.

Thanks once again for the help!

[shelloutput.txt](https://github.com/zeek/broker/files/7489333/shelloutput.txt)
[CMakeError.log](https://github.com/zeek/broker/files/7489335/CMakeError.log)
[CMakeOutput.log](https://github.com/zeek/broker/files/7489336/CMakeOutput.log)

**Comment by timwoj** [comment]
From the shell output, it appears you might be missing the submodules. Try running `git submodules update --init --recursive` from the top-level broker directory.

**Comment by CrutzPan** [comment]
That solved the problem. Thank you so much!

**Comment by CrutzPan** [comment]
Hey again, i am still not able to compile my C Code with broker..i am getting a lot of undefined references. I am still using the same system and compiler..can you help me here? I have no idea what the issue is. Thank you!  Sorry for the repeated questions!
[shellout.txt](https://github.com/zeek/broker/files/7491403/shellout.txt)
.

**Comment by Neverlord** [comment]
> g++ -std=c++17 broker.c -o test

That's not an issue with Broker. You're not telling the compiler where to find the symbols. For GCC, you need to use `-l<lib>` and `-L<path>` options for that. Either that or setting up a CMake project to manage the dependencies. Please refer to general guides on how to link to libraries or writing CMake files.
