### ISSUE TITLE
Python bindings fail with mutable index types

### ISSUE THREAD

**Issue by ckreibich** [zeek/broker#205]
Zeek supports mutable index types in containers (for example, a set of records that contain tables), but Python has a rule that index types must be immutable. When Broker encounters such a structure, it crashes. Here's an example:

test.zeek:
```
redef exit_only_after_terminate=T;

type Foo: record {
        config: table[string] of string;
};

global foo: event(s: set[Foo]);

event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string) {
        local s: set[Foo] = set(Foo($config = table()));
        Broker::publish("foo", foo, s);
}

event zeek_init() {
        Broker::listen();
}
```

test.py:
```
#! /usr/bin/env python

# export PYTHONPATH=$PYTHONPATH:$(zeek-config --python_dir)
import broker

ep = broker.Endpoint()
sub = ep.make_subscriber("foo")

ep.peer("127.0.0.1", 9999)
sub.get()
```

Run `zeek ./test.zeek` in one shell, then `python ./test.py` in another, and you get:
```
$ python /test.py 
Traceback (most recent call last):
  File "/home/christian/t1/./test.py", line 10, in <module>
    sub.get()
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 140, in get
    return (msg[0].string(), Data.to_py(msg[1]))
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 544, in to_py
    return converters[d.get_type()]()
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 540, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in to_vector
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in <genexpr>
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 544, in to_py
    return converters[d.get_type()]()
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 540, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in to_vector
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in <genexpr>
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 544, in to_py
    return converters[d.get_type()]()
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 540, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in to_vector
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 517, in <genexpr>
    return tuple(Data.to_py(i) for i in v)
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 544, in to_py
    return converters[d.get_type()]()
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 534, in <lambda>
    Data.Type.Set: lambda: to_set(d.as_set()),
  File "/home/christian/inst/opt/zeek/lib64/zeek/python/broker/__init__.py", line 511, in to_set
    return set([Data.to_py(i) for i in s])
TypeError: unhashable type: 'dict'
```
This is a well-known problem and the solutions are all variants of making a `dict` derivative hashable. See [here](https://stackoverflow.com/questions/1151658/python-hashable-dicts) for examples. Guido shooting down a `frozendict` PEP is also [worth a read](https://www.python.org/dev/peps/pep-0416/).

So the following is a workaround:

```
-- i/bindings/python/broker/__init__.py
+++ w/bindings/python/broker/__init__.py
@@ -68,6 +68,10 @@
 Configuration = _broker.Configuration
 BrokerOptions = _broker.BrokerOptions

+class HashableDict(dict):
+    def __hash__(self):
+        return hash(frozenset(self))
+
 # Broker's (or better: CAF's) EC code is an integer. Add support
 # for comparision against the enum.
 _EC_eq = _broker.EC.__eq__
@@ -511,7 +515,8 @@
             return set([Data.to_py(i) for i in s])

         def to_table(t):
-            return {Data.to_py(k): Data.to_py(v) for (k, v) in t.items()}
+            tmp = {Data.to_py(k): Data.to_py(v) for (k, v) in t.items()}
+            return HashableDict(tmp.items())

         def to_vector(v):
             return tuple(Data.to_py(i) for i in v)
```

This is clearly incomplete since there can be other combinations of types that would lead to the error. Plus, the object structure returned by `get()` would then have unexpected behaviors in it. One idea is to allow callers to explicitly state that they won't modify the result, perhaps via a separate API or `get(immutable=True)`.

**Comment by rsmmr** [comment]
> One idea is to allow callers to explicitly state that they won't modify the result, perhaps via a separate API or `get(immutable=True)`.

I like some version of a seperate API this the best so far, in the immutable case we can then just generally return something that doesn't allow changes (using whatever approach works best for that). But I'm not sure how to pass the information down (i.e., here: how to get `MappingProxyType` into `to_table()` I guess). One other idea: we could work with a module-level global that people set to define the behavior, like 

```
import broker
broker.InmutableValues = True
```

Then the `broker` module can just branch on that wherever it needs to.

**Comment by ckreibich** [comment]
Robin I looked at this a bit further. I could see the following:

- We derive `broker.ImmutableData` from `broker.Data` (or vice versa?). It features the same `to_py()` API, but whenever mutability is a concern, it does what's needed to appease Python (e.g. use of `frozenset`) and tucks the `MappingProxyType` wrapper onto returned results to achieve read-only status.
- This leaves the question of how to ensure the use of `ImmutableData`. Three levels come to mind: (1) new API to `Subscriber`, (2) a new Subscriber, (3) a global switch. I actually like the idea of a `Subscriber` subclass, something like `SafeSubscriber` — there's some precedent to that naming elsewhere in Python. The global strikes me as a bit harsh...

I looked at the C++ side of things too but didn't see anything there (like a previously unexposed API aspect, say) that would be relevant here.

What do you think?

**Comment by ckreibich** [comment]
I omitted one thing: users don't create `Subscriber` instances themselves, it happens via `Endpoint.make_subscriber`. So the API question would shift to that method — we could have a new `Endpoint.make_safe_subscriber()`, or a class argument to `make_subscriber` that defaults to `Subscriber`. We could implement the former via the latter.
