### ISSUE TITLE
Build is broken on Windows

### ISSUE THREAD

**Issue by timwoj** [zeek/broker#213]
I'm trying to build with VS 2022. It builds fine from the 2.2.0 tag, but fails on `master`.

**Comment by Neverlord** [comment]
This should have been flagged by Travis, but apparently Windows builds (silently?) stopped a while ago.

**Comment by timwoj** [comment]
I started looking into getting our Cirrus Windows builds going again on
Friday but I ran out of time to finish it. I'll keep looking at it when I'm
back tomorrow.

**Comment by Neverlord** [comment]
@timwoj thanks for bringing back MSVC builds! I have updated the ALM branch and #201 has (working) Windows builds back as well. Closing here.
