### ISSUE TITLE
Unable to exchange messages between a zeek endpoint and a python endpoint

### ISSUE THREAD

**Issue by joemkeen** [zeek/broker#237]
I am wondering if I am in a version conflict here.  I am able to exchange messages between two zeek implemented endpoints. I am also able to exchange messages between two python implemented endpoints.  However I can not exchange messages between a zeek implemented endpoint and a python implemented endpoint.  I do see the connection being made via netstat, however I do not see the peer added event on either side.

zeek version 4.2.2-0
broker version 2.3.0
python version 3.8.10

Side note: Like the idea of a websocket I/F

THANKS!

**Comment by Neverlord** [comment]
Yes, that may be a version mismatch. Zeek 4.2.2 seems to have Broker in version 2.2.0. Either that or one side is using encryption and the other does not.

The network protocol unfortunately isn't backwards compatible. But with the new Broker release, we have a version handshake for peers that hopefully means we can do backwards compatible changes on the wire protocol past Zeek 5.0.

**Comment by joemkeen** [comment]
I had a chance to play a bit more with this. I grabbed the nightly build of
5.1.  Got things working with a small change to the example code.  It seems
we get two events before we are connected.  The first is an
EndpointDiscovered and the second is the PeerAdded.

...

# Wait until connection is established.
    connected = False;

    while not connected:
        st = ss.get()
        if  (type(st) == broker.Status and st.code() ==
broker.SC.PeerAdded):
            print ("Connected")
            connected = True
        else:
            print("Not connect: " + str(st.code()))

...


Thanks for the response


Joe Keen

System Architecture and Design

Motorola Solutions

847-454-6509


On Tue, Jun 14, 2022 at 12:34 PM Dominik Charousset <
***@***.***> wrote:

> Yes, that may be a version mismatch. Zeek 4.2.2 seems to have Broker in
> version 2.2.0. Either that or one side is using encryption and the other
> does not.
>
> The network protocol unfortunately isn't backwards compatible. But with
> the new Broker release, we have a version handshake for peers that
> hopefully means we can do backwards compatible changes on the wire protocol
> past Zeek 5.0.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zeek_broker_issues_237-23issuecomment-2D1155499210&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=koh1ArX_JO-ouFH-eDmw_qsdAwui7y7lrdezT8wckIU&m=Qd4nLBghR6X1AiWtenrpTDQF36XX29dneIbEfe2LkmIWuBmhqA1CqqNTug0pz0ez&s=GhyNSMgMe8lIr9MX6PP3a4Mg7rwt-Kt-xRuz-dACZNM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AASCUSMBLEMM75N5WNY4J6TVPC7DPANCNFSM5YYDUU4Q&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=koh1ArX_JO-ouFH-eDmw_qsdAwui7y7lrdezT8wckIU&m=Qd4nLBghR6X1AiWtenrpTDQF36XX29dneIbEfe2LkmIWuBmhqA1CqqNTug0pz0ez&s=j3dg9q7mkax1nnRKh-w4Es39XmqVSTZwzL3dGpSulBU&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

-- 


*For more information on how and why we collect your personal 
information, please visit our Privacy Policy 
<https://www.motorolasolutions.com/en_us/about/privacy-policy.html?elqTrackId=8980d888905940e39a2613a7a3dcb0a7&elqaid=2786&elqat=2#privacystatement>.*
