### ISSUE TITLE
Allow deterministic node IDs

### ISSUE THREAD

**Issue by J-Gras** [zeek/broker#253]
For seeded Zeek runs (`zeek -G random.seed`), Node IDs will still vary as they seem to be based on process IDs. If this isn't too complicated or breaks other things, having deterministic node IDs in seeded runs would be handy for testing.

**Comment by Neverlord** [comment]
Nothing to do here, there's already an API for that. 🙂

I've filed a PR to make the required adjustments in Zeek.
