### ISSUE TITLE
Build warnings from recent `convert` changes

### ISSUE THREAD

**Issue by timwoj** [zeek/broker#257]
It's kind of a lot, so I put them in a text file. Most of them look like they're related but they're used in a lot of places.

[warnings.txt](https://github.com/zeek/broker/files/9114104/warnings.txt)

**Comment by AmazingPP** [comment]
I found that the warnings in the type traits part were caused by GCC bugs.

[Bug 89070](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89070) - Attribute [[nodiscard]] should be ignored in unevaluated contexts
