### ISSUE TITLE
Activity related to unused broker store

### ISSUE THREAD

**Issue by J-Gras** [zeek/broker#311]
Doing some performance measurements in a local cluster, I peeked at the raw broker communication using Justin's
`tcpdump -n -i lo0 -c 1000 -A | egrep '[a-zA-Z:_-]{5,}' -io|egrep ':|-' | sort|uniq  -c|sort -rn` filtering approach. Looking at the results, communication related to a broker store that wasn't used caught my eye:
```
854 ::known_log_certs_with_broker
 432 processed-messages
 360 buffered-messages
 144 routing-update
  72 web-socket
  72 store-unacknowledged-updates
  72 store-processed-updates
  72 store-output-channels
  72 store-input-channels
  72 running-actors
  72 rejected-messages
...
```
I obtained the above numbers using the following reproducer script (`zeek -j test-broker.zeek`, 1000 packets took me about one minute):
```zeek
module Test;

redef Log::default_rotation_interval = 0secs;
redef Broker::disable_ssl = T;
redef Cluster::retry_interval = 1sec;

event zeek_init()
	{
	if ( ! Supervisor::is_supervisor() )
		return;

	local cluster: table[string] of Supervisor::ClusterEndpoint;
	cluster["manager"] = [$role=Supervisor::MANAGER, $host=127.0.0.1, $p=10000/tcp];
	cluster["worker"] = [$role=Supervisor::WORKER, $host=127.0.0.1, $p=10001/tcp];

	for ( n, ep in cluster )
		{
		local sn = Supervisor::NodeConfig($name=n);
		sn$cluster = cluster;
		sn$directory = n;

		local res = Supervisor::create(sn);

		if ( res != "" )
			print fmt("supervisor failed to create node '%s': %s", n, res);
		}
	}
```
As there is no traffic processed, I would have expected the `known_log_certs` store to be quite. Commenting out the [store](
https://github.com/zeek/zeek/blob/6bf1091a03c6cadc30e417a66881bedd98764671/scripts/base/files/x509/main.zeek#L95) and [some extra lines](https://github.com/zeek/zeek/blob/6bf1091a03c6cadc30e417a66881bedd98764671/scripts/base/files/x509/main.zeek#L146-L149), the traffic is gone.

Running this using `BROKER_CONSOLE_VERBOSITY=debug zeek -B broker -j test-broker.zeek` I could neither spot anything in the `debug.log` nor in the console output that seemed to be related to this communication. However, the presence of the _unused_ store had a noticeable impact on the performance in my original test setup. Maybe this related to https://github.com/zeek/zeek/issues/2803.

**Comment by Neverlord** [comment]
The stores always have some level of communication. Initially for setting up the communication and then they send heartbeat messages for making sure master and clones stay in sync.

However, does `854 ::known_log_certs_with_broker` mean that there are 854 packages for this store? Heartbeats should be two per second (https://github.com/zeek/broker/blob/master/include/broker/defaults.hh#L41), so that would be too much for a 60-second run.

I'm a bit confused by the next line that states `432 processed-messages`. If the number for log-certs represents the messages exchanged for that store, how could that be greater than the total number?

**Comment by Neverlord** [comment]
> 854 ... would be too much for a 60-second run.

Uh, wait. This is a cluster. 🙂

How many nodes? The heartbeats are per master/clone pair.

**Comment by J-Gras** [comment]
> I'm a bit confused by the next line that states `432 processed-messages`. If the number for log-certs represents the messages exchanged for that store, how could that be greater than the total number?

Actually the number does not represent the number of messages. The command just greps through the raw traffic and counts strings that look similar to event names. For example, the occurrences of `known_log_certs_with_broker` in the telemetry updates are counted as well.

> Heartbeats should be two per second (https://github.com/zeek/broker/blob/master/include/broker/defaults.hh#L41), so that would be too much for a 60-second run.

Thanks a lot for the pointer! By adapting the value I could confirm the traffic is indeed heartbeat related.
