### ISSUE TITLE
Broker metrics port setting overriding BROKER_METRICS_PORT env variable

### ISSUE THREAD

**Issue by timwoj** [zeek/broker#350]
I encountered this recently on a system that wasn't setting the port number for metrics correctly on a manager node, but only the manager node. After a quick bisect on Zeek, it looks like it actually might be a problem in broker. This shell snippet reproduces it:

```
BROKER_METRICS_PORT=1234 zeek Broker::metrics_port=9911/tcp -e 'event zeek_init() { print Broker::metrics_port; }'
```

That should return `1234/tcp` but it's always returning `9911/tcp`. The bisect traced it to https://github.com/zeek/zeek/commit/d1eb0f47fdf772c197e711befd96be46d9e38bd2, which included a bunch of broker/CAF updates to support GCC 13. That merge includes https://github.com/zeek/broker/commit/bace54b5795a9fa1ec283a5e5f06cc2df66223a5 which seems suspicious, but according to a quick pass in a debugger everything gets set correctly.

I confirmed that reverting that commit out of broker fixes the issue and it starts reporting the correct port number again.

**Comment by timwoj** [comment]
I'd consider this a blocker for the zeek 6.0 release.

**Comment by Neverlord** [comment]
I'll take care of it.
