### ISSUE TITLE
Missing compatibility list for Zeek

### ISSUE THREAD

**Issue by zoumath19** [zeek/broker#393]
Can I find somewhere which Zeek Broker version works with which Zeek version? I'm currently having an issue with my containers not having aligned versions.

Example my ZEEK_BROKER_VERSION=2.5.0 what would be valid values for ZEEK_VERSION?

**Comment by Neverlord** [comment]
Out of curiosity, how did you end up with mismatched versions? Building Zeek from source should always give you the proper versions and the binary distributions should be consistent as well.

@timwoj is this maybe documented in the Zeek releases? `NEWS` and `CHANGES` don't seem to mention submodule versions, but I know you're cutting new Broker versions for Zeek releases.

My only idea would be checking out Zeek tags and see what Broker version they point to.

**Comment by timwoj** [comment]
We made a decision recently to not do versioned releases of the various submodules alongside the Zeek releases, mostly for the reasons brought up in this issue. We started implementing this decision with the 6.2 release.

You should absolutely prefer to use the version included with each Zeek release. Any other version is not guaranteed to work and you may run into many subtle issues.
