### ISSUE TITLE
Broker include broken

### ISSUE THREAD

**Issue by J-Gras** [zeek/broker#399]
I have some external project that uses Zeek's `FindBroker.cmake` to link against broker. With the current zeek master the build stopped working. Configure exists with the following error:
```
CMake Error at /usr/local/zeek/share/zeek/cmake/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Broker (missing: BROKER_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/zeek/share/zeek/cmake/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  my-proj/cmake/FindBroker.cmake:74 (find_package_handle_standard_args)
  my-proj/CMakeLists.txt:14 (find_package)
```
Comparing with installs of previous Zeek versions, I noticed `config.hh` missing in `include/broker`. Maybe it's related to https://github.com/zeek/broker/commit/3c64a311d802348f020eaf3eda3042d4d9cb4b1d.

**Comment by vpax** [comment]
@Neverlord any update on this? It continues to bite us :-(

**Comment by Neverlord** [comment]
Thank you for the ping! Really sorry for the wait here. This fell off my radar because I got knocked out for a couple weeks by a really bad flu last month.

@J-Gras I have patch ready in `issue/gh-399`. Mind double-checking before I open up a PR?
