### ISSUE TITLE
Consider using UTC timezone in python bindings

### ISSUE THREAD

**Issue by makarchuk** [zeek/broker#40]
Currently time formatter for the `Time` type is specified like this
```
 Data.Type.Timestamp: lambda: datetime.datetime.fromtimestamp(d.as_timestamp())
```

This can creates a naive datetime object with no timezone attached to it, which makes it very inconvinient to user, since he is forced to transform it to timezone aware object and look current timezone up.

It would be much more convinient to use if converter was something like this
`lambda: datetime.datetime.utcfromtimestamp(d.as_timestamp()).replace(tz_info=pytz.utc())`

TZ aware time objects are better than TZ unaware. Always.

**Comment by jsiwek** [comment]
Thanks for the suggestion, it's patched now in `master`.
