### ISSUE TITLE
Connection failure using Python bindings

### ISSUE THREAD

**Issue by pevandenburie** [zeek/broker#41]
Hi there

I downloaded last Broker (7dab576) based on CAF 0.16.3, and installed it using ```virtualenv``` exactly as in [tutorial](https://docs.zeek.org/projects/broker/en/stable/python.html#installation-in-a-virtual-environment). 

I'm working on last SecurityOnion using Bro version 2.6.1.

I tried the ```ping``` [example](https://docs.zeek.org/projects/broker/en/stable/python.html#exchanging-bro-events), to check it was working:

    $ bro ping.bro

Then:

    $ . ./venv/bin/activate
    (venv)$ python ping.py

But then it stays stuck in call to ```ep.peer("127.0.0.1", 9999, 10)``` !

I checked the connection was possible:

    $ nc -zv 127.0.0.1 9999
    Connection to 127.0.0.1 9999 port [tcp/*] succeeded!

In Wireshark, the TLS hanshake seems to restart continuously, from ```Client Hello``` to ```Application Data```.

At least, having both listener and subscriber in same Python script (as in [doc](https://docs.zeek.org/projects/broker/en/stable/python.html#communication)) seems to work!

Any idea about what could possibly go wrong?

Thanks!

**Comment by pevandenburie** [comment]
Also, creating a peer in a .bro script works :

```
redef exit_only_after_terminate = T;

event bro_init()
	{
	Broker::peer("127.0.0.1", 9999/tcp);
	}

event Broker::peer_added(endpoint: Broker::EndpointInfo, msg: string)
	{
	print "peer added", endpoint;
	terminate();
	}
```

Then:

    $ bro pong.bro 
    peer added, [id=7D0AE96CF0BBAFF999E209DE1CE77A1D46A69D00#9429, network=[address=127.0.0.1, bound_port=9999/tcp]]

Could this be a CAF version mismatch between the one included in Bro version 2.6.1 and the one from Broker 7dab576 ?

**Comment by jsiwek** [comment]
Latest Broker and the one from Bro 2.6.1 speak different/incompatible message formats, so that's more likely the issue than the CAF 0.16.2 versus 0.16.3 difference.  Trying to align the versions is my suggestion: either use master branch of both Bro and Broker, or use Bro 2.6.1 + Broker 1.1.2.

**Comment by pevandenburie** [comment]
Thanks a lot @jsiwek !
It works now... I just had to remind to ```git submodule update```... and then again in 3rdparty/  ! ;-)
