### ISSUE TITLE
Passing a Record as Event data

### ISSUE THREAD

**Issue by pevandenburie** [zeek/broker#42]
Hello
Is there a way we could pass a Record as Event data?

I mean, the Python 'dict' is mapped to Bro Table type, which restrict the dict having all values of the same type ('string' for example). 

But a Record could contain different values types (a timestamp, an int counter, a string description).

Or maybe there is a workaround to pass 'Record' between Bro and Python through Broker ?

Thanks :-)

**Comment by mavam** [comment]
Broker doesn't carry Zeek's types, just the plain data. If you expect a record with `n` fields, then you can send a Python list `xs` with `len(xs) == n`.

**Comment by jsiwek** [comment]
As Matthias said, a Python list can be used and it will get converted into the appropriate Bro record on the receiver.  Here's an example:

```bro
# ping.bro

redef exit_only_after_terminate = T;

type myrec: record {
	n: count;
	s: string;
};

global pong: event(mr: myrec);

event ping(mr: myrec)
	{
	print "got ping", mr;
	event pong(mr);
	}

event bro_init()
	{
	Broker::subscribe("/topic/test");
	Broker::listen("127.0.0.1", 9999/tcp);
	Broker::auto_publish("/topic/test", pong);
	}
```

```python
# ping.py

import sys
import broker

# Setup endpoint and connect to Bro.
ep = broker.Endpoint()
sub = ep.make_subscriber("/topic/test")
ss = ep.make_status_subscriber(True);
ep.peer("127.0.0.1", 9999)

# Wait until connection is established.
st = ss.get()

if not (type(st) == broker.Status and st.code() == broker.SC.PeerAdded):
    print("could not connect")
    sys.exit(0)

for n in range(5):
    # Send event "ping(n)".
    ping = broker.bro.Event("ping", [broker.Count(n), "hi"]);
    ep.publish("/topic/test", ping);

    # Wait for "pong" reply event.
    (t, d) = sub.get()
    pong = broker.bro.Event(d)
    print("received {}{}".format(pong.name(), pong.args()))
```

Note a potential pitfall is the difference in 'count' versus 'int': Python itself has no distinction so we need to be explicit and use the `broker.Count` type.  There may be other pitfalls like that which don't come to mind at the moment, so you should provide specific examples of what you're trying if you have further trouble.

**Comment by pevandenburie** [comment]
Hi @mavam and @jsiwek
Thanks a lot that’s exactly I was looking for... did not figure it was so simple :-)
