### ISSUE TITLE
Broker event queues behaviour

### ISSUE THREAD

**Issue by Olerdrive** [zeek/broker#46]
I've got some questions on broker events and how they behave in edge cases as i haven't found any details covering it in documentation.

- Will it cause a memory leak in zeek when i publish events in some script.bro to some topic with no alive subscriber? As i see that does not happen, store.bro [documentation](https://docs.zeek.org/en/stable/scripts/base/frameworks/broker/store.bro.htm) does not actually figures it out

- How to investigate a size of published to some topic events queue using broctl/programmatically? 

Thanks in advance for the clarification

**Comment by jsiwek** [comment]
> * Will it cause a memory leak in zeek when i publish events in some script.bro to some topic with no alive subscriber?

No, those should just get dropped if, at time of publication, no one is subscribed.

> * How to investigate a size of published to some topic events queue using broctl/programmatically?

Don't think there's currently a way to check the number of peers that will match a given topic.  I see just `endpoint::peers` (can check current number of peers) and `endpoint::peer_subscriptions` (can check the topics to which any current peer has subscribed).  If you need something more, please open a feature request issue (or a PR would be great, too).
