### ISSUE TITLE
Build fails with libc++-8.0 on case-insensitive file systems

### ISSUE THREAD

**Issue by tobim** [zeek/broker#51]
Steps to reproduce:
1. Configure broker with clang-8 and an accompanying libc++ on darwin. The toolchain can be obtained from Homebrew for example: `brew install --with-toolchain llvm`
2. run `make` in the build dir.

Result:
```
In file included from /Users/tobim/tenzir/vast/aux/broker/broker/src/data.cc:1:
In file included from /Users/tobim/tenzir/vast/aux/broker/broker/broker/data.hh:4:
In file included from /nix/store/9fykw9zr14n7palmkcd74x6x2x5yraf4-libc++-8.0.0/include/c++/v1/utility:200:
In file included from /nix/store/9fykw9zr14n7palmkcd74x6x2x5yraf4-libc++-8.0.0/include/c++/v1/__tuple:15:
In file included from /nix/store/9fykw9zr14n7palmkcd74x6x2x5yraf4-libc++-8.0.0/include/c++/v1/cstddef:38:
/Users/tobim/tenzir/vast/aux/broker/broker/version:1:1: error: expected unqualified-id
1.2.0-4
```
This happens because a <version> header is going to be added to the standard library in C++20, and libc++ already implements it. Technically this is a bug in libc++, as the header should probably not be included with `-std=c++17` and lower, however I consider the chances to get it "fixed" upstream as low. 

I suggest to move the `broker` directory to `include/broker` so the projects root directory does not need to be added to the include directories.

**Comment by tobim** [comment]
I would open a PR if there are no objections to the suggested fix.

**Comment by tobim** [comment]
I somehow managed to forget to tell that the responsible header is `<version>`, and it clashes with the `VERSION` file.

**Comment by jsiwek** [comment]
Headers are moved into `include/broker/` now in `master` via https://github.com/zeek/broker/commit/90af8ad56bb9a7bfbe4b449a6d6b0aaa2ce108a2

**Comment by tobim** [comment]
Thanks for the fix!
