### ISSUE TITLE
broker-cluster-benchmark sometimes fails to terminate

### ISSUE THREAD

**Issue by jsiwek** [zeek/broker#66]
Sometimes `broker-cluster-benchmark` doesn't terminate.  E.g. running with the following recordings:

[zeek-broker-recordings.tar.gz](https://github.com/zeek/broker/files/3753458/zeek-broker-recordings.tar.gz)

It sometimes terminates cleanly and other times (maybe every 5-ish times for me) hangs for several minutes so I assume it's not going to terminate.  Here's the verbose output from one of those times:

[broker-cluster-bench-hang.txt](https://github.com/zeek/broker/files/3753460/broker-cluster-bench-hang.txt)

I was able to run the benchmark 40 times without hanging by adding a 2 second `sleep()` after this line:

https://github.com/zeek/broker/blob/b3251b1d6944e398bb97ba824210b895fd886827/tests/benchmark/broker-cluster-benchmark.cc#L1138

So guessing something in the node setup for the benchmark isn't correctly waiting for peerings/subscriptions to be fully established before nodes start sending messages?

**Comment by Neverlord** [comment]
I'm unable to reproduce this with the recordings you've provided. I've tested on my developer box (MacMini, Quad Core) as well as on an AMD Opteron box (CentOS 7, 32 cores). I noticed that the benchmark produces log files and I've [fixed that](https://github.com/zeek/broker/pull/68), but debug and release build both run for me (tested 50x each).

What OS/HW setup are you using? Do you pass any build flags to CAF/Broker other than the build type?

**Comment by Neverlord** [comment]
After running it a bunch more, I've finally seen it in the release build. I'll dig into it some more.

**Comment by jsiwek** [comment]
Thanks for looking into that, combination of #69 and #71 helped me (or at least can now run the benchmark 100 times without hanging where before it was on the order of 10).
