### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by rsmmr** [zeek/broker#88]
The `python-data` fails for me because of a type mismatch for integers:

```
======================================================================
FAIL: test_integer (__main__.TestDataConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "data.py", line 112, in test_integer
    self.check_to_broker_and_back(42, '42', broker.Data.Type.Integer)
  File "data.py", line 104, in check_to_broker_and_back
    self.check_to_py(b, p)
  File "data.py", line 58, in check_to_py
    self.assertIsInstance(b2p, type(p))
AssertionError: 42 is not an instance of <type 'long'>
```

`type(42)` says it's a `<type 'int'>` (not long).

Anybody else seeing that?

**Comment by jsiwek** [comment]
Yes, but just with `python2`.  There does exist some py2/py3 compat logic in the test, so maybe it actually no longer applies or got broke on some past update to pybind.  Generally, not too inclined to investigate much if we just plan to drop `python2` support.

**Comment by Neverlord** [comment]
Isn't Python 2 officially end of life by now?

**Comment by jsiwek** [comment]
Yeah, there's no reason to try to fix anything specific to Python2 IMO.

Here was an umbrella/overview I had for actively removing Python2 support: https://github.com/zeek/zeek/issues/706
Hasn't been a high priority yet since the current state of things should still work fine for everyone and isn't getting in the way of anything.

**Comment by rsmmr** [comment]
Getting this out for 4.0 would be helpful as then we won't need to support it during that LTS cycle.
